### ISSUE TITLE
Initial implementation known issues

### ISSUE THREAD

**Issue by roll** [openspending/os-cli#25]
- [x] config system uses `None` - do not require .openspendingrc because of default config?
- [ ] Using just API keys approach let any user to write everywhere on Open Spending flat data store
- [ ] odd problem with `goodtable` - version `0.5.6` still uses `jtskit` in the code. As a workaround we install `jtskit<0.5`

**Comment by pwalsh** [comment]
moved to https://github.com/openspending/openspending/issues/886
