### ISSUE TITLE
Misleading structure for .openspendingrc

### ISSUE THREAD

**Issue by danfowler** [openspending/os-cli#29]
In the [README.md](https://github.com/openspending/os-cli/blob/master/README.md), it says the following:

> A config file looks something like this:

```
# .openspendingrc

{
    "api_key": ""
}
```

However, the `.openspendingrc` file is read as an ordinary JSON file which causes the tool to raise the following error:

```
ValueError: Config file is not valid
```

**Comment by pwalsh** [comment]
That snippet is valid json. I'm not sure what the issue is here.

**Comment by danfowler** [comment]
The comment above the valid JSON: `# .openspendingrc`

It led me to believe I could have a comment like that in my .openspendingrc file.

**Comment by pwalsh** [comment]
Oh. That is quite a common idiom used in read me files to indicate the name of the file for the following snippet.

**Comment by roll** [comment]
FIXED
